NPNLCD.LcdInit()
NPNLCD.ShowString("Xin chao", 0, 0)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P2, 0)
    music.startMelody(music.builtInMelody(Melodies.Birthday), MelodyOptions.Once)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 1)
    music.startMelody(music.builtInMelody(Melodies.Birthday), MelodyOptions.Once)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(1000)
    NPNLCD.LcdInit()
    NPNLCD.ShowString("七七", 0, 0)
    basic.pause(1000)
    NPNLCD.ShowString("一千只猫薄禾", 0, 0)
    basic.pause(1000)
    NPNLCD.clear()
})
